// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE9QzyofSH7rquD0tfzRsuRxGNo5ppN28',
    appId: '1:692732084232:web:663231fde1e95b7f20d1bd',
    messagingSenderId: '692732084232',
    projectId: 'authenticationapp-cb3ba',
    authDomain: 'authenticationapp-cb3ba.firebaseapp.com',
    storageBucket: 'authenticationapp-cb3ba.firebasestorage.app',
    measurementId: 'G-H1LFWYPTL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZ3y2_ypIl-_8idVO29GuvSoRbRua-bc',
    appId: '1:692732084232:android:67a51101360753a220d1bd',
    messagingSenderId: '692732084232',
    projectId: 'authenticationapp-cb3ba',
    storageBucket: 'authenticationapp-cb3ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsBY72uQ8cxHRctoj-JlbZ4rpDgx_mhu0',
    appId: '1:692732084232:ios:dc2759e94dfe325520d1bd',
    messagingSenderId: '692732084232',
    projectId: 'authenticationapp-cb3ba',
    storageBucket: 'authenticationapp-cb3ba.firebasestorage.app',
    iosBundleId: 'com.example.moviereviewapp',
  );
}
